In [2]:
import pandas as pd
import numpy as np


file_path = "../Data/random_pc_r_5_da_2_bal/all_preds_gramneg_capsid.pkl"
df = pd.read_pickle(file_path)
display(df.head(10))

,Vibrio_capsid,Pseudomonas_capsid,Salmonella_capsid,Microcystis_capsid,Escherichia_capsid,Ralstonia_capsid,Klebsiella_capsid,Xanthomonas_capsid,Edwardsiella_capsid,Pseudoalteromonas_capsid,...,Caulobacter_capsid,Dickeya_capsid,Cronobacter_capsid,Cellulophaga_capsid,Rhodobacter_capsid,Pectobacterium_capsid,Providencia_capsid,Serratia_capsid,Pelagibacter_capsid,Shewanella_capsid
proteinID,,,,,,,,,,,,,,,,,,,,,
AB002632_00003,0.892029,0.006306,0.009383,0.081754,0.041862,0.003088,0.015248,0.004815,0.000388,0.006762,...,0.007589,0.025637,0.003450,0.002163,0.000379,0.000957,0.024976,0.001247,0.000841,0.006299
AB002632_00005,0.884198,0.039370,0.016259,0.015769,0.091740,0.374117,0.007287,0.480330,0.003258,0.004493,...,0.002441,0.002847,0.002345,0.004689,0.000276,0.004016,0.009124,0.000302,0.001409,0.137713
AB002632_00006,0.960939,0.002251,0.005723,0.007318,0.034375,0.000299,0.008497,0.001767,0.003222,0.001731,...,0.000707,0.002753,0.001835,0.005969,0.000040,0.004501,0.005529,0.001472,0.002281,0.019812
AB002632_00007,0.887575,0.009491,0.011740,0.021452,0.247610,0.040026,0.000952,0.375594,0.001234,0.001174,...,0.005451,0.006769,0.002275,0.001705,0.000650,0.002436,0.008512,0.000485,0.001534,0.379902
AB008550_00005,0.003117,0.052489,0.009547,0.012469,0.173586,0.781633,0.570038,0.000270,0.000731,0.447287,...,0.007142,0.000516,0.022271,0.000672,0.002136,0.008286,0.017155,0.003673,0.013043,0.015565
AB012573_00004,0.930251,0.003667,0.018491,0.020558,0.042870,0.148061,0.006463,0.374860,0.003355,0.002323,...,0.002935,0.003018,0.001120,0.005009,0.000345,0.001802,0.008174,0.000345,0.002840,0.059651
AB012573_00005,0.911129,0.003276,0.005064,0.007209,0.024449,0.000183,0.011092,0.001888,0.002095,0.002478,...,0.000969,0.002576,0.001442,0.002717,0.000047,0.004390,0.004646,0.000875,0.002123,0.006736
AB012573_00006,0.930109,0.345965,0.014381,0.012753,0.030696,0.096792,0.012413,0.140725,0.001117,0.001413,...,0.001485,0.003171,0.005401,0.001524,0.000589,0.002018,0.004833,0.002042,0.002331,0.017938
AB012574_00004,0.930251,0.003667,0.018491,0.020558,0.042870,0.148061,0.006463,0.374860,0.003355,0.002323,...,0.002935,0.003018,0.001120,0.005009,0.000345,0.001802,0.008174,0.000345,0.002840,0.059651
AB012574_00005,0.911129,0.003276,0.005064,0.007209,0.024449,0.000183,0.011092,0.001888,0.002095,0.002478,...,0.000969,0.002576,0.001442,0.002717,0.000047,0.004390,0.004646,0.000875,0.002123,0.006736

In [3]:
file_path = "../Data/random_pc_r_5_da_2_bal/all_preds_gramneg_adsorption-related.pkl"
df = pd.read_pickle(file_path)
# display(df.head(10))
display(df)

,Vibrio_adsorption-related,Pseudomonas_adsorption-related,Salmonella_adsorption-related,Microcystis_adsorption-related,Escherichia_adsorption-related,Ralstonia_adsorption-related,Klebsiella_adsorption-related,Xanthomonas_adsorption-related,Edwardsiella_adsorption-related,Pseudoalteromonas_adsorption-related,...,Caulobacter_adsorption-related,Dickeya_adsorption-related,Cronobacter_adsorption-related,Cellulophaga_adsorption-related,Rhodobacter_adsorption-related,Pectobacterium_adsorption-related,Providencia_adsorption-related,Serratia_adsorption-related,Pelagibacter_adsorption-related,Shewanella_adsorption-related
proteinID,,,,,,,,,,,,,,,,,,,,,
AB002632_00006,0.969125,0.007314,0.006941,0.003694,0.005458,0.000366,0.000599,0.005198,0.018867,0.010280,...,0.000869,0.000262,0.001218,0.000538,8.210613e-07,0.008083,0.002361,0.000135,2.734884e-05,0.749314
AB008550_00017,0.000129,0.948174,0.032622,0.022008,0.030797,0.870878,0.016700,0.117543,0.127999,0.000338,...,0.000417,0.000640,0.001096,0.000007,2.251798e-04,0.008219,0.005208,0.003320,2.194374e-05,0.050493
AB008550_00021,0.001836,0.988712,0.004281,0.012209,0.020828,0.058833,0.000613,0.002595,0.061032,0.000005,...,0.000486,0.001563,0.011443,0.000019,4.671957e-04,0.002666,0.020523,0.001069,3.445678e-07,0.010482
AB008550_00022,0.000398,0.131704,0.006134,0.063325,0.024078,0.103821,0.003888,0.002345,0.307049,0.001491,...,0.036255,0.000150,0.001644,0.000003,1.219674e-04,0.003465,0.000516,0.002195,1.926214e-05,0.001919
AB012573_00005,0.989906,0.002179,0.010661,0.003602,0.010071,0.000314,0.000342,0.003989,0.005301,0.009542,...,0.000493,0.000140,0.002040,0.000352,2.036275e-06,0.007876,0.002967,0.000086,2.216401e-05,0.475998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
X60322_00009,0.022871,0.021480,0.160223,0.024638,0.256285,0.002611,0.005813,0.008404,0.500000,0.000472,...,0.002404,0.016008,0.003942,0.000042,5.489515e-07,0.012935,0.002696,0.004033,8.009545e-06,0.024021
X60323_00008,0.008813,0.006514,0.046738,0.084230,0.303295,0.078908,0.004152,0.004653,0.210072,0.000110,...,0.010652,0.141659,0.005678,0.000020,6.464040e-06,0.086459,0.002083,0.011971,6.446449e-06,0.003350
Y13918_00017,0.000129,0.948174,0.032622,0.022008,0.030797,0.870878,0.016700,0.117543,0.127999,0.000338,...,0.000417,0.000640,0.001096,0.000007,2.251798e-04,0.008219,0.005208,0.003320,2.194374e-05,0.050493
Y13918_00021,0.001836,0.988712,0.004281,0.012209,0.020828,0.058833,0.000613,0.002595,0.061032,0.000005,...,0.000486,0.001563,0.011443,0.000019,4.671957e-04,0.002666,0.020523,0.001069,3.445678e-07,0.010482
Y13918_00022,0.000398,0.131704,0.006134,0.063325,0.024078,0.103821,0.003888,0.002345,0.307049,0.001491,...,0.036255,0.000150,0.001644,0.000003,1.219674e-04,0.003465,0.000516,0.002195,1.926214e-05,0.001919

In [4]:
import os

# Get the list of all files and directories
# Remove the leading slash
path = "../Data/random_pc_r_5_da_2_bal"
files = os.listdir(path)

for file in files:
    print(file)

all_preds_grampos_terminase.pkl
all_preds_grampos_adsorption-related.pkl
all_preds_gramneg_spanin.pkl
all_preds_gramneg_val.pkl
all_preds_gramneg_cell_wall_depolymerase.pkl
all_preds_gramneg_transcriptional_activator.pkl
all_preds_gramneg_endolysin.pkl
all_preds_gramneg_super_infection.pkl
all_preds_grampos_transcriptional_repressor.pkl
all_preds_gramneg_transcriptional_repressor.pkl
all_preds_grampos_DNA_polymerase.pkl
all_preds_grampos_nuclease.pkl
all_preds_gramneg_DNA-associated_1.pkl
all_preds_grampos_sir2.pkl
all_preds_grampos_tail.pkl
all_preds_gramneg_tail_sheath.pkl
all_preds_gramneg_nucleotide_metabolism.pkl
all_preds_grampos_spanin.pkl
all_preds_grampos_integration.pkl
all_preds_grampos_transferase.pkl
all_preds_gramneg_nuclease.pkl
all_preds_gramneg_replication_initiation.pkl
all_preds_gramneg_reductase.pkl
all_preds_grampos_nucleotide_metabolism.pkl
all_preds_grampos_transcriptional_regulator.pkl
all_preds_gramneg_integration.pkl
all_preds_gramneg_lysis.pkl
all_preds_gramneg_sir2.pkl
all_preds_gramneg_adsorption-related.pkl
all_preds_grampos_transcriptional_activator.pkl
all_preds_grampos_tail_sheath.pkl
all_preds_gramneg_tail.pkl
all_preds_gramneg_pvp.pkl
all_preds_gramneg_terminase.pkl
all_preds_grampos_anti-restriction.pkl
all_preds_grampos_DNA-associated.pkl
all_preds_gramneg_holin.pkl
all_scores_testset.csv
all_preds_gramneg_primase.pkl
all_preds_grampos_lysis_inhibitor.pkl
all_preds_grampos_lysis.pkl
all_preds_gramneg_baseplate.pkl
all_preds_gramneg_ejection.pkl
all_preds_gramneg_lysin.pkl
all_preds_grampos_reductase.pkl
all_preds_gramneg_transferase.pkl
all_preds_grampos_portal.pkl
all_preds_grampos_capsid.pkl
all_preds_gramneg_annealing.pkl
all_preds_grampos_endolysin.pkl
all_preds_gramneg_transcriptional_regulator.pkl
all_preds_grampos_head-tail_joining.pkl
all_preds_gramneg_DNA_polymerase.pkl
all_preds_gramneg_capsid.pkl
all_preds_gramneg_anti-restriction.pkl
all_preds_grampos_replication_initiation.pkl
all_preds_grampos_val.pkl
all_preds_gramneg_DNA-associated.pkl
all_preds_grampos_super_infection.pkl
all_preds_gramneg_portal.pkl
.ipynb_checkpoints
all_preds_grampos_annealing.pkl
all_preds_grampos_cell_wall_depolymerase.pkl
all_preds_grampos_tail_appendage.pkl
all_preds_gramneg_lysis_inhibitor.pkl
all_preds_gramneg_helicase.pkl
all_preds_gramneg_packaging_assembly.pkl
all_preds_grampos_helicase.pkl
all_preds_grampos_phosphorylation.pkl
all_preds_gramneg_toxin.pkl
all_preds_grampos_lysin.pkl
all_preds_gramneg_head-tail_joining.pkl
all_preds_grampos_RNA-associated.pkl
all_preds_gramneg_phosphorylation.pkl
all_preds_grampos_primase.pkl
all_preds_grampos_toxin.pkl
all_preds_grampos_ejection.pkl
all_preds_grampos_pvp.pkl
all_preds_grampos_holin.pkl
all_scores_trainset.csv
all_preds_gramneg_tail_appendage.pkl
all_preds_grampos_baseplate.pkl
all_preds_gramneg_RNA-associated.pkl
all_preds_grampos_packaging_assembly.pkl

In [5]:
file_path = "../Data/all_random_pc_splits.pkl"
df = pd.read_pickle(file_path)
# display(df.head(10))
display(df)

,split_Campylobacter_lysin,split_Campylobacter_endolysin,split_Campylobacter_val,split_Caulobacter_lysin,split_Caulobacter_endolysin,split_Caulobacter_val,split_Cellulophaga_lysin,split_Cellulophaga_endolysin,split_Cellulophaga_val,split_Citrobacter_lysin,...,split_Streptococcus_val,split_Propionibacterium_lysin,split_Propionibacterium_endolysin,split_Propionibacterium_val,split_Streptomyces_lysin,split_Streptomyces_endolysin,split_Streptomyces_val,split_Paenibacillus_lysin,split_Paenibacillus_endolysin,split_Paenibacillus_val
proteinID,,,,,,,,,,,,,,,,,,,,,
AB002632_00001,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB002632_00002,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB002632_00003,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB002632_00004,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB002632_00005,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Z47794_00023,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z47794_00024,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z47794_00025,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z47794_00026,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z47794_00027,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
file_path = "../Data/embeddings.pkl"
df = pd.read_pickle(file_path)
# display(df.head(10))
display(df)

,0,1,2,3,4,5,6,7,8,9,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
proteinID,,,,,,,,,,,,,,,,,,,,,
AB002632_00001,0.013371,-0.035044,-0.035994,0.057320,0.019145,0.011627,-0.008765,-0.042639,-0.068923,-0.020869,...,-0.019392,0.021964,-0.113666,-0.006445,0.020138,0.066324,0.028932,0.031009,-0.000508,0.006072
AB002632_00002,0.022211,-0.091248,0.051000,0.059318,-0.033121,0.009205,0.000173,-0.129266,-0.086850,0.041821,...,0.004320,-0.035122,-0.030564,-0.097199,0.027926,-0.069824,0.021567,-0.000767,0.063039,0.049864
AB002632_00003,0.062245,-0.033898,0.070273,-0.030639,0.024119,0.014112,-0.011854,-0.071408,-0.026129,-0.031357,...,-0.001526,-0.035334,0.004621,-0.072579,-0.059717,0.010773,0.061313,0.076676,0.024803,-0.007698
AB002632_00004,0.018732,0.050848,0.009785,0.000267,-0.057730,0.011694,0.013670,-0.043879,0.040709,-0.022060,...,-0.022331,-0.087253,-0.005146,-0.048122,0.003712,-0.010861,0.024868,0.092215,0.023578,-0.094987
AB002632_00005,0.027054,-0.093019,0.016626,-0.004320,0.064356,0.010339,0.025468,-0.086796,-0.108033,0.048534,...,-0.047721,-0.010484,0.162168,-0.022955,-0.025515,-0.092842,0.010686,0.009989,0.073957,0.105771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Z47794_00023,0.022563,0.003806,0.028419,-0.096477,-0.009286,-0.009857,0.040491,-0.035146,0.038400,-0.015016,...,-0.055055,-0.026897,0.008487,-0.086155,-0.035160,0.017889,0.000466,0.066644,0.021230,-0.102147
Z47794_00024,-0.005002,0.022848,0.080614,-0.017445,-0.008448,0.016226,0.003459,-0.177612,-0.043051,0.015238,...,-0.054578,-0.101374,0.000876,-0.150207,-0.022624,-0.004242,-0.030535,-0.008345,0.015613,-0.010397
Z47794_00025,-0.014739,0.036652,0.030701,-0.027894,-0.072174,0.049856,0.012308,-0.141062,0.067927,0.011871,...,-0.019445,-0.024630,-0.027289,0.009869,0.041196,0.057598,-0.031133,0.055995,0.012680,-0.004419
Z47794_00026,0.035646,0.125420,-0.044289,-0.032611,-0.042168,0.014855,0.002917,-0.073774,0.056612,-0.007126,...,-0.047758,-0.052914,-0.037782,-0.031976,0.004138,0.004054,0.032592,0.003849,0.020384,-0.035117
Z47794_00027,0.045422,-0.006953,-0.006277,0.002371,0.003399,-0.022768,-0.001160,-0.080828,0.025439,0.015884,...,-0.047640,-0.074306,-0.042256,-0.041912,-0.016067,-0.048328,0.017032,0.090568,0.007555,-0.030389

In [7]:
file_path = "../Data/functional_predictions.pkl"
df = pd.read_pickle(file_path)
# display(df.head(10))
display(df)

,lysin,endolysin,val,pvp,capsid,major_capsid,minor_capsid,tail,major_tail,minor_tail,...,reductase,crispr,anti-restriction,sir2,toxin,super_infection,lysis,lysis_inhibitor,holin,spanin
proteinID,,,,,,,,,,,,,,,,,,,,,
AB002632_00001,0.001376,NaN,NaN,0.046736,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000130,0.000006,0.000259,0.000022,0.000527,0.000142,0.002954,NaN,NaN,NaN
AB002632_00002,0.000007,NaN,NaN,0.017311,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000142,0.000012,0.001421,0.000008,0.000293,0.000098,0.000421,NaN,NaN,NaN
AB002632_00003,0.000215,NaN,NaN,0.582806,0.978879,0.008960,0.973580,0.009338,NaN,NaN,...,0.000249,0.000016,0.000549,0.000012,0.000362,0.000266,0.090401,NaN,NaN,NaN
AB002632_00004,0.000719,NaN,NaN,0.066260,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000482,0.000011,0.000249,0.000026,0.000008,0.000427,0.091976,NaN,NaN,NaN
AB002632_00005,0.000038,NaN,NaN,0.995377,0.992280,0.999998,0.001371,0.003364,NaN,NaN,...,0.001202,0.000026,0.000505,0.000005,0.000177,0.000623,0.016366,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Z47794_00023,0.000323,NaN,NaN,0.080922,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000813,0.000014,0.002483,0.000028,0.000652,0.000978,0.001953,NaN,NaN,NaN
Z47794_00024,0.000753,NaN,NaN,0.029592,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000637,0.000017,0.000652,0.000035,0.000137,0.000089,0.153119,NaN,NaN,NaN
Z47794_00025,0.000090,NaN,NaN,0.044169,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000999,0.000009,0.045569,0.000042,0.032074,0.000049,0.001275,NaN,NaN,NaN
Z47794_00026,0.000369,NaN,NaN,0.018680,NaN,NaN,NaN,NaN,NaN,NaN,...,0.008881,0.000018,0.007444,0.000059,0.000341,0.000220,0.001727,NaN,NaN,NaN
Z47794_00027,0.000233,NaN,NaN,0.010475,NaN,NaN,NaN,NaN,NaN,NaN,...,0.001325,0.000030,0.137845,0.000007,0.001128,0.000817,0.017098,NaN,NaN,NaN